import type { ImageSourcePropType } from 'react-native';
import type { FoodVisualKey } from '@fitnessapp/shared';

const suppliedFoodImages = {
  artichoke: require('../../assets/food/catalog/artichoke.png'),
  asparagus: require('../../assets/food/catalog/asparagus.png'),
  onion: require('../../assets/food/catalog/onion.png'),
  broccoli: require('../../assets/food/catalog/broccoli.png'),
  okra: require('../../assets/food/catalog/okra.png'),
  carrot: require('../../assets/food/catalog/carrot.png'),
  'butternut-squash': require('../../assets/food/catalog/butternut-squash.png'),
  pumpkin: require('../../assets/food/catalog/pumpkin.png'),
  zucchini: require('../../assets/food/catalog/zucchini.png'),
  lettuce: require('../../assets/food/catalog/lettuce.png'),
  eggplant: require('../../assets/food/catalog/eggplant.png'),
  cilantro: require('../../assets/food/catalog/cilantro.png'),
  'white-or-red-cabbage': require('../../assets/food/catalog/white-or-red-cabbage.png'),
  cauliflower: require('../../assets/food/catalog/cauliflower.png'),
  leek: require('../../assets/food/catalog/leek.png'),
  turnip: require('../../assets/food/catalog/turnip.png'),
  'hearts-of-palm': require('../../assets/food/catalog/hearts-of-palm.png'),
  cucumber: require('../../assets/food/catalog/cucumber.png'),
  chard: require('../../assets/food/catalog/chard.png'),
  sprouts: require('../../assets/food/catalog/sprouts.png'),
  celery: require('../../assets/food/catalog/celery.png'),
  tomato: require('../../assets/food/catalog/tomato.png'),
  'cherry-tomatoes': require('../../assets/food/catalog/cherry-tomatoes.png'),
  parsley: require('../../assets/food/catalog/parsley.png'),
  mushrooms: require('../../assets/food/catalog/mushrooms.png'),
  'bell-pepper': require('../../assets/food/catalog/bell-pepper.png'),
  radish: require('../../assets/food/catalog/radish.png'),
  kohlrabi: require('../../assets/food/catalog/kohlrabi.png'),
  'summer-squash': require('../../assets/food/catalog/summer-squash.png'),
  kale: require('../../assets/food/catalog/kale.png'),
  'green-or-yellow-beans': require('../../assets/food/catalog/green-or-yellow-beans.png'),
  fennel: require('../../assets/food/catalog/fennel.png'),
  spinach: require('../../assets/food/catalog/spinach.png'),
  'baby-corn': require('../../assets/food/catalog/baby-corn.png'),
  watermelon: require('../../assets/food/catalog/watermelon.png'),
  pear: require('../../assets/food/catalog/pear.png'),
  cherimoya: require('../../assets/food/catalog/cherimoya.png'),
  'fresh-pineapple': require('../../assets/food/catalog/fresh-pineapple.png'),
  persimmon: require('../../assets/food/catalog/persimmon.png'),
  peach: require('../../assets/food/catalog/peach.png'),
  grapefruit: require('../../assets/food/catalog/grapefruit.png'),
  banana: require('../../assets/food/catalog/banana.png'),
  guava: require('../../assets/food/catalog/guava.png'),
  cherries: require('../../assets/food/catalog/cherries.png'),
  quince: require('../../assets/food/catalog/quince.png'),
  'fresh-lychee': require('../../assets/food/catalog/fresh-lychee.png'),
  melon: require('../../assets/food/catalog/melon.png'),
  mango: require('../../assets/food/catalog/mango.png'),
  apricot: require('../../assets/food/catalog/apricot.png'),
  nectarine: require('../../assets/food/catalog/nectarine.png'),
  'prickly-pear': require('../../assets/food/catalog/prickly-pear.png'),
  grapes: require('../../assets/food/catalog/grapes.png'),
  'passion-fruit': require('../../assets/food/catalog/passion-fruit.png'),
  papaya: require('../../assets/food/catalog/papaya.png'),
  kiwi: require('../../assets/food/catalog/kiwi.png'),
  clementine: require('../../assets/food/catalog/clementine.png'),
  'star-fruit': require('../../assets/food/catalog/star-fruit.png'),
  pomegranate: require('../../assets/food/catalog/pomegranate.png'),
  plum: require('../../assets/food/catalog/plum.png'),
  loquat: require('../../assets/food/catalog/loquat.png'),
  'fresh-fig': require('../../assets/food/catalog/fresh-fig.png'),
  orange: require('../../assets/food/catalog/orange.png'),
  apple: require('../../assets/food/catalog/apple.png'),
  strawberry: require('../../assets/food/catalog/strawberry.png'),
  berries: require('../../assets/food/catalog/berries.png'),
  'dried-fruit': require('../../assets/food/catalog/dried-fruit.png'),
  'sweet-potato': require('../../assets/food/catalog/sweet-potato.png'),
  potatoes: require('../../assets/food/catalog/potatoes.png'),
  beetroot: require('../../assets/food/catalog/beetroot.png'),
  rice: require('../../assets/food/catalog/rice.png'),
  beans: require('../../assets/food/catalog/beans.png'),
  lentils: require('../../assets/food/catalog/lentils.png'),
  peas: require('../../assets/food/catalog/peas.png'),
  chickpeas: require('../../assets/food/catalog/chickpeas.png'),
  'fresh-fruit': require('../../assets/food/catalog/fresh-fruit.png'),
  'thick-rolled-oats': require('../../assets/food/catalog/thick-rolled-oats.png'),
  quinoa: require('../../assets/food/catalog/quinoa.png'),
  buckwheat: require('../../assets/food/catalog/buckwheat.png'),
  corn: require('../../assets/food/catalog/corn.png'),
  edamame: require('../../assets/food/catalog/edamame.png'),
  'pearl-barley': require('../../assets/food/catalog/pearl-barley.png'),
  'skinny-pasta': require('../../assets/food/catalog/skinny-pasta.png'),
  tahini: require('../../assets/food/catalog/tahini.png'),
  butter: require('../../assets/food/catalog/butter.png'),
  'cooking-oil': require('../../assets/food/catalog/cooking-oil.png'),
  olives: require('../../assets/food/catalog/olives.png'),
  avocado: require('../../assets/food/catalog/avocado.png'),
  'peanut-butter': require('../../assets/food/catalog/peanut-butter.png'),
  'almond-butter': require('../../assets/food/catalog/almond-butter.png'),
  'nuts-almonds': require('../../assets/food/catalog/nuts-almonds.png'),
  'coconut-products': require('../../assets/food/catalog/coconut-products.png'),
  eggs: require('../../assets/food/catalog/eggs.png'),
  fish: require('../../assets/food/catalog/fish.png'),
  chicken: require('../../assets/food/catalog/chicken.png'),
  meat: require('../../assets/food/catalog/meat.png'),
  'dairy-products': require('../../assets/food/catalog/dairy-products.png'),
  tofu: require('../../assets/food/catalog/tofu.png'),
  seitan: require('../../assets/food/catalog/seitan.png'),
  'diet-cola': require('../../assets/food/catalog/diet-cola.png'),
  'dry-wine': require('../../assets/food/catalog/dry-wine.png'),
  beer: require('../../assets/food/catalog/beer.png'),
  honey: require('../../assets/food/catalog/honey.png'),
} satisfies Partial<Record<FoodVisualKey, ImageSourcePropType>>;

export const SUPPLIED_FOOD_IMAGE_KEYS = Object.keys(
  suppliedFoodImages,
) as FoodVisualKey[];

export const foodImageAssetFor = (
  visualKey: FoodVisualKey,
): ImageSourcePropType | undefined => suppliedFoodImages[
  visualKey as keyof typeof suppliedFoodImages
];
